/**
 * @file Automatically generated by barrelsby.
 */

export { default as AssessmentsPage } from "./AssessmentsPage";
export * from "./AssessmentsPage";
export { default as FormPage } from "./FormPage";
export * from "./FormPage";
export { default as HomePage } from "./HomePage";
export * from "./HomePage";
export { default as KonsentrasiPage } from "./KonsentrasiPage";
export * from "./KonsentrasiPage";
export { default as LoginPage } from "./LoginPage";
export * from "./LoginPage";
export { default as MapPage } from "./MapPage";
export * from "./MapPage";
export { default as OkupasiPage } from "./OkupasiPage";
export * from "./OkupasiPage";
export { default as RegisterPage } from "./RegisterPage";
export * from "./RegisterPage";
export { default as SekolahPage } from "./SekolahPage";
export * from "./SekolahPage";
export { default as UsersManagement } from "./UsersManagement";
export * from "./UsersManagement";
